name: release

# TODO uncomment this once Uber billing plan includes access to GitHub Actions
#on:
#  push:
#    tags:
#      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Golang
        uses: actions/setup-go@master
        with:
            go-version: '1.12'
      - name: Do release
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
